### PR TITLE
onboarding screen

### PR DESCRIPTION
**Pull request by ismaelAbogabal**
1- Implement the onboarding screen 
2- fix previous issues 
3- implement splash screen background image

### CODE REVIEW

**Comment by ismaelAbogabal** [comment]
@mr-ym

**Review by mr-ym — CHANGES_REQUESTED** [review]
Fix required, test are done under Android TV 1080p SDK 30

- About screen overflowing
image

- Update application: the toast displays "Please Rate Application", correct the text please

**Review by omar-cherif — APPROVED** [review]

**Review by mr-ym — CHANGES_REQUESTED** [review]
Remarks:

- Fix socials on About page: Fix links and remove unused social medias
- Change string text when click on "Update Application"

**Comment by omar-cherif** [comment]
Dear Youssouf @mr-ym,
The social icons are managed from the backend.
URL: https://alpha.mawaqit.net/android/views/index.php?page=social
image

**Comment by omar-cherif** [comment]
@mr-ym social icons edited from the backend, I removed the unused ones and kept the 3 listed below :
image

**Comment by ibrahim-zehhaf-mawaqit** [comment]
on witch device have you tested it on browserstack ?

**Comment by omar-cherif** [comment]
Galaxy Tab S7

**Pull request merged**
