### PR TITLE
fix(Compatibility with Xiaomi Box3): Set camera and faketouch feature

### PR DESCRIPTION
**Pull request by mmammar**
fix(Compatibility with Xiaomi Box3): Set camera and faketouch features to required=false

### CODE REVIEW

**Review by ibrahim-zehhaf-mawaqit — APPROVED** [review]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Unfortunately always ko on my xiaomi android box

**Review by mr-ym — DISMISSED** [review]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@mmammar have you test it on an android box ?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> @mmammar have you test it on an android box ?

Yes on my mibox3 please see screenshots above

**Comment by mmammar** [comment]
@ibrahim-zehhaf-mawaqit I do not have android box. Is it still saying "Not compatible"

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> @ibrahim-zehhaf-mawaqit I do not have android box. Is it still saying "Not compatible"

yes https://github.com/mawaqit/android-tv/pull/12#issuecomment-1030881444

**Comment by mmammar** [comment]
@ibrahim-zehhaf-mawaqit Please verify now.

**Review by ibrahim-zehhaf — APPROVED** [review]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
please fix conflict

**Review by ibrahim-zehhaf-mawaqit — APPROVED** [review]

**Comment by omar-cherif** [comment]
@ismael-abogabal-mawaqit Could you please review these changes and check if they are correct ?
Brother @ibrahim-zehhaf-mawaqit is saying that the Xiaomi Box is still incompatible.

**Pull request merged**
